USER_COLLECTION_NAME = 'user'
TOKEN_COLLECTION_NAME = 'token'
MODELS_COLLECTION_NAME = 'models'
PROPERTIES_SCHEMA_COLLECTION_NAME = 'properties_schema'
OBJECTS_COLLECTION_NAME = 'objects'
AUTH_LOG_COLLECTION_NAME = 'auth_log'

list_collections = [
  USER_COLLECTION_NAME,
  TOKEN_COLLECTION_NAME,
  MODELS_COLLECTION_NAME,
  PROPERTIES_SCHEMA_COLLECTION_NAME,
  OBJECTS_COLLECTION_NAME,
  AUTH_LOG_COLLECTION_NAME
]
